### ISSUE TITLE
Safari sometimes not loading pixel animation

### ISSUE THREAD

**Issue by robizzt** [JamesNimlos/pixel-flow#3]
Hello,
I'm using Pixel Flow gradient animation on every page of my website. But sometimes animation doesn't start when I open page. And when I refresh that same page, animation starts normally. Console doesn't shows any error, and with console.logs in "tick" function I found out that animation happens, but canvas doesn't render it somehow. 
Problem happens only in Safari browser (both MacBook Pro and iPhone).

Am I doing something wrong or is it Safari problem?

This is my code:
```
var funcOpts = [{
	lg: { location: [-1, -0.5, 0.7, 1], resolution : [800, 0] }
}];
function startPixelAnimation() {
	// Pixel
	var $pixelImgs = $('.pixel-wrapper img');
	Promise.all($pixelImgs.map(function(_, pixelImg) {
		return waitForImage(pixelImg);
	})).then(function() {
		$pixelImgs.PixelFlow({ resolution: 32});

		var $pixelImgWrapper = $('.pixel-wrapper');

		var pixelFlow = $pixelImgWrapper.find('canvas').data('plugin_PixelFlow');

		pixelFlow.offsetX = pixelFlow.width;

		TweenMax.fromTo(pixelFlow, 2, {
				offsetX: pixelFlow.width,
				autoCSS: false
			}, {
				offsetX: 0,
				autoCSS: false,
				onUpdate: tick,
				roundProps: 'offsetX',
				onUpdateParams: ['{self}', pixelFlow]
			}
		);

		function tick(tween, pF) {
			pF.linearGradient(funcOpts[0].lg);
		}
	});
}
```
PS. I'm using Pixel Flow with Fullpage.js, but I think that should not be a problem.

**Comment by JamesNimlos** [comment]
That's interesting, I think you're right that Fullpage.js should not be an issue. I'll have to do some investigation later today and see if I can reproduce.

**Comment by robizzt** [comment]
There is no need. I figured it out.
Problem was that code for Pixel Flow was not in same .html file.
Since code for Pixel Flow was same for every page, I pasted it in scripts.js and it wasn't working. But when I pasted it in every .html file separately, it was working. I don't know why.

**Comment by JamesNimlos** [comment]
That's unexpected; I hate when there is some unknown issue, but I'm really glad you were able to fix it! Feel free to reach out again if you'd like help debugging in the future 👍
